[build]
cmd = "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"

[deploy]
startCommand = "gunicorn petadoption.wsgi:application --bind 0.0.0.0:$PORT"